name: Update Beecrowd Stats
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4
          
      - name: Scrape Beecrowd stats
        run: |
          python .github/scripts/scrape_beecrowd.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/beecrowd-stats.json
          git commit -m "Automated: Update Beecrowd stats" || echo "No changes to commit"
          git push
