name: Update Beecrowd Stats
on:
  schedule:
    - cron: '0 12 * * 0' # Every Sunday at 12:00 UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create data directory
        run: |
          mkdir -p data
          if [ ! -f data/beecrowd-stats.json ]; then
            echo '{"rank":"--","solved":"--","points":"--","last_updated":"","status":"Initial"}' > data/beecrowd-stats.json
          fi

      - name: Run Beecrowd Scraper
        run: |
          python .github/scripts/scrape_beecrowd.py
          cat data/beecrowd-stats.json

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/beecrowd-stats.json
          git diff --quiet && git diff --cached --quiet || \
          (git commit -m "Automated: Update Beecrowd stats [skip ci]" && \
           git push)
